# Generated by Django 5.1.7 on 2025-03-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='imágen'),
        ),
    ]
